// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import SliceTest from './SliceTest';

export {
	CallToAction,
	SliceTest,
};

export const components = {
	call_to_action: CallToAction,
	slice_test: SliceTest,
};
