import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { createClient } from "../prismicio";
import { CallToAction } from "../slices";
import Image from "next/image";


const Home: NextPage = ({ page }: any) => {
  console.log(page.data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1>{page.data.titre[0].text}</h1>
        <Image src={page.data.img.url} width="200" height="200" />
      </section>
    </div>
  );
};

export default Home;

export async function getStaticProps({ previewData }: any) {
  const client = createClient({ previewData });

  const page = await client.getByUID("autrepage", "1");

  return {
    props: { page }, // Will be passed to the page component as props
  };
}
